const CpanelData = [
    {
      id: 1,
      cardVpsTitle: "cPanel 1",
      cardVpsSubTitle: "Optimal solution for Beginners", 
      cardAnchorLink: `/cPanel`,
      cardVpsImg: "https://madpopo.com/image/PopoStarter.png",
      cardVpsAltName: `cPanel 1`,
      cardVpsOgPrice: `$23`,
      cardVpsWebSpace: "4",
      cardVpsCapacity: "8",
      cardVpsCapacity2: "50 GB",
      cardVpsCapacity3: "200 GB",
      cardVpsSnap: "1",
      cardVpsOPt1: "Free Domain 1st Year*",
      cardVpsOPT2: `1`,
      cardVpsOPT3: `10`,
      cardVpsOPT4: `20`,
      cardVpsOPT5: `2`,
      cardVpsOPT6: `Weekly Backup`,
      priceYearlyInINR: 10,
      priceTwoYearlyInINR: 20,
      priceThreeYearlyInINR: 30,
      priceYearlyInUSD: 11,
      priceTwoYearlyInUSD: 21,
      priceThreeYearlyInUSD: 31,
      priceYearlyInEUR: 12,
      priceTwoYearlyInEUR: 22,
      priceThreeYearlyInEUR: 32,
    },
    {
      id: 2,
      cardVpsTitle: "cPanel 2 ",
      cardVpsSubTitle: "Ideal for personal websites",
      cardAnchorLink: `/cPanel`,
      cardVpsImg: `https://madpopo.com/image/PopoPro.png`,
      cardVpsAltName: `cPanel 2 `,
      cardVpsOgPrice: `$24`,
      cardVpsWebSpace: "6",
      cardVpsCapacity: "16",
      cardVpsCapacity2: "100 GB",
      cardVpsCapacity3: "400 GB",
      cardVpsSnap: "2",
      cardVpsOPt1: "Free Domain 1st Year*",
      cardVpsOPT2: `5`,
      cardVpsOPT3: `20`,
      cardVpsOPT4: `50`,
      cardVpsOPT5: `10`,
      cardVpsOPT6: `Weekly Backup`,
      priceYearlyInINR: 40,
      priceTwoYearlyInINR: 50,
      priceThreeYearlyInINR: 60,
      priceYearlyInUSD: 41,
      priceTwoYearlyInUSD: 51,
      priceThreeYearlyInUSD: 61,
      priceYearlyInEUR: 42,
      priceTwoYearlyInEUR: 52,
      priceThreeYearlyInEUR: 62,
    },
    {
      id: 3,
      cardVpsTitle: "cPanel 3",
      cardVpsSubTitle: "Suitable for small business.",
      cardAnchorLink: `/cPanel`,
      cardVpsImg: `https://madpopo.com/image/PopoGrow.png`,
      cardVpsAltName: `cPanel 3`,
      cardVpsOgPrice: `$25`,
      cardVpsWebSpace: "10",
      cardVpsCapacity: "60",
      cardVpsCapacity2: "400 GB",
      cardVpsCapacity3: "1.6 TB",
      cardVpsSnap: "4",
      cardVpsOPt1: "Free Domain 1st Year*",
      cardVpsOPT2: `10`,
      cardVpsOPT3: `30`,
      cardVpsOPT4: `100`,
      cardVpsOPT5: `20`,
      cardVpsOPT6: `Daily Backup`,
      priceYearlyInINR: 70,
      priceTwoYearlyInINR: 80,
      priceThreeYearlyInINR: 90,
      priceYearlyInUSD: 71,
      priceTwoYearlyInUSD: 81,
      priceThreeYearlyInUSD: 91,
      priceYearlyInEUR: 72,
      priceTwoYearlyInEUR: 82,
      priceThreeYearlyInEUR: 92,
    },
  ];
  export default CpanelData;
  