const CoLocationServerData = [
    {
      id: 1,
      dsCardTitle: "Co-Location 1",
      dsCardSubTitle: "Optimal solution for Beginners",
      cardAnchorLink: `/dedicated-server`,
      dsCardImg: "https://madpopo.com/static/media/PopoStarter.png",
      dsCardAltName: `PopoStarter`,
      dsCardOgPrice: `$23`,
      dsCardWebSpace: "4",
      dsCardCapacity: "8",
      dsCardCapacity2: "50 GB",
      dsCardCapacity3: "200 GB",
      dsCardSnap: "1",
      dsCardOPt1: "Free Domain 1st Year*",
      dsCardOPT2: `1`,
      dsCardOPT3: `10`,
      dsCardOPT4: `20`,
      dsCardOPT5: `2`,
      dsCardOPT6: `Weekly Backup`,
      priceYearlyInINR: 120,
      priceTwoYearlyInINR: 140,
      priceThreeYearlyInINR: 150,
      priceYearlyInUSD: 13,
      priceTwoYearlyInUSD: 14,
      priceThreeYearlyInUSD: 17,
      priceYearlyInEUR: 12,
      priceTwoYearlyInEUR: 13,
      priceThreeYearlyInEUR: 16,
    },
    {
      id: 2,
      dsCardTitle: "Co-Location 2 ",
      dsCardSubTitle: "Ideal for personal websites",
      cardAnchorLink: `/dedicated-server`,
      dsCardImg: `https://madpopo.com/static/media/PopoPro.png`,
      dsCardAltName: `PopoPro `,
      dsCardOgPrice: `$24`,
      dsCardWebSpace: "6",
      dsCardCapacity: "16",
      dsCardCapacity2: "100 GB",
      dsCardCapacity3: "400 GB",
      dsCardSnap: "2",
      dsCardOPt1: "Free Domain 1st Year*",
      dsCardOPT2: `5`,
      dsCardOPT3: `20`,
      dsCardOPT4: `50`,
      dsCardOPT5: `10`,
      dsCardOPT6: `Weekly Backup`,
      priceYearlyInINR: 220,
      priceTwoYearlyInINR: 240,
      priceThreeYearlyInINR: 250,
      priceYearlyInUSD: 23,
      priceTwoYearlyInUSD: 24,
      priceThreeYearlyInUSD: 27,
      priceYearlyInEUR: 22,
      priceTwoYearlyInEUR: 23,
      priceThreeYearlyInEUR: 26,
    },
    {
      id: 3,
      dsCardTitle: "Co-Location 3",
      dsCardSubTitle: "Suitable for small business.",
      cardAnchorLink: `/dedicated-server`,
      dsCardImg: `https://madpopo.com/static/media/PopoGrow.png`,
      dsCardAltName: `PopoGrow`,
      dsCardOgPrice: `$25`,
      dsCardWebSpace: "10",
      dsCardCapacity: "60",
      dsCardCapacity2: "400 GB",
      dsCardCapacity3: "1.6 TB",
      dsCardSnap: "4",
      dsCardOPt1: "Free Domain 1st Year*",
      dsCardOPT2: `10`,
      dsCardOPT3: `30`,
      dsCardOPT4: `100`,
      dsCardOPT5: `20`,
      dsCardOPT6: `Daily Backup`,
      priceYearlyInINR: 320,
      priceTwoYearlyInINR: 340,
      priceThreeYearlyInINR: 350,
      priceYearlyInUSD: 33,
      priceTwoYearlyInUSD: 34,
      priceThreeYearlyInUSD: 37,
      priceYearlyInEUR: 32,
      priceTwoYearlyInEUR: 33,
      priceThreeYearlyInEUR: 36,
    },
  ];
  export default CoLocationServerData;
  