const BusinessEmailData = [
  {
    id: 1,
    busEmailTitle: "Plan 1",
    busEmailSubTitle: "Optimal solution for Beginners",
    cardAnchorLink: `/VirtualDedicatedServer`,
    busEmailImg: "https://madpopo.com/image/PopoStarter.png",
    busEmailAltName: `PopoStarter`,
    busEmailOgPrice: `$23`,
    busEmailWebSpace: "4",
    busEmailCapacity: "8",
    busEmailCapacity2: "50 GB",
    busEmailCapacity3: "200 GB",
    busEmailSnap: "1",
    busEmailOPt1: "Free Domain 1st Year*",
    busEmailOPT2: `1`,
    busEmailOPT3: `10`,
    busEmailOPT4: `20`,
    busEmailOPT5: `2`,
    busEmailOPT6: `Weekly Backup`,
    priceYearlyInINR: 449,
    priceTwoYearlyInINR: 419,
    priceThreeYearlyInINR: 399,
    priceYearlyInUSD: 6.6,
    priceTwoYearlyInUSD: 5.3,
    priceThreeYearlyInUSD: 4.9,
    priceYearlyInEUR: 6,
    priceTwoYearlyInEUR: 5,
    priceThreeYearlyInEUR: 4,
    width: 131,
    height: 165,
  },
  {
    id: 2,
    busEmailTitle: "Plan 2 ",
    busEmailSubTitle: "Ideal for personal websites",
    cardAnchorLink: `/VirtualDedicatedServer`,
    busEmailImg: `https://madpopo.com/image/PopoPro.png`,
    busEmailAltName: `PopoPro `,
    busEmailOgPrice: `$24`,
    busEmailWebSpace: "6",
    busEmailCapacity: "16",
    busEmailCapacity2: "100 GB",
    busEmailCapacity3: "400 GB",
    busEmailSnap: "2",
    busEmailOPt1: "Free Domain 1st Year*",
    busEmailOPT2: `5`,
    busEmailOPT3: `20`,
    busEmailOPT4: `50`,
    busEmailOPT5: `10`,
    busEmailOPT6: `Weekly Backup`,
    priceYearlyInINR: 549,
    priceTwoYearlyInINR: 519,
    priceThreeYearlyInINR: 499,
    priceYearlyInUSD: 7.6,
    priceTwoYearlyInUSD: 7.3,
    priceThreeYearlyInUSD: 6.9,
    priceYearlyInEUR: 7.2,
    priceTwoYearlyInEUR: 7,
    priceThreeYearlyInEUR: 6,
    width: 131,
    height: 165,
  },
  {
    id: 3,
    busEmailTitle: "Plan 3",
    busEmailSubTitle: "Suitable for small business.",
    cardAnchorLink: `/VirtualDedicatedServer`,
    busEmailImg: `https://madpopo.com/image/PopoGrow.png`,
    busEmailAltName: `PopoGrow`,
    busEmailOgPrice: `$25`,
    busEmailWebSpace: "10",
    busEmailCapacity: "60",
    busEmailCapacity2: "400 GB",
    busEmailCapacity3: "1.6 TB",
    busEmailSnap: "4",
    busEmailOPt1: "Free Domain 1st Year*",
    busEmailOPT2: `10`,
    busEmailOPT3: `30`,
    busEmailOPT4: `100`,
    busEmailOPT5: `20`,
    busEmailOPT6: `Daily Backup`,
    priceYearlyInINR: 749,
    priceTwoYearlyInINR: 719,
    priceThreeYearlyInINR: 699,
    priceYearlyInUSD: 9.6,
    priceTwoYearlyInUSD: 9.3,
    priceThreeYearlyInUSD: 8.9,
    priceYearlyInEUR: 9.2,
    priceTwoYearlyInEUR: 9,
    priceThreeYearlyInEUR: 8,
    width: 131,
    height: 165,
  },
];
export default BusinessEmailData;
