const DDSData2 = [
  {
    id: 1,
    cardVpsTitle: "Starter",
    cardVpsSubTitle: "Optimal solution for Beginners", 
    cardAnchorLink: `/virtual-server`,
    cardVpsImg: "https://madpopo.com/static/media/PopoStarter.png",
    cardVpsAltName: `Starter`,
    cardVpsOgPrice: `$23`,
    cardVpsWebSpace: "6",
    cardVpsCapacity: "E5 2620 v3",
    cardVpsCapacity2: "16 GB",
    cardVpsCapacity3: "250 GB SSD",
    cardVpsSnap: "2 TB",
    cardVpsOPt1: "Free Domain 1st Year*",
    cardVpsOPT2: `1`,
    cardVpsOPT3: `10`,
    cardVpsOPT4: `20`,
    cardVpsOPT5: `2`,
    cardVpsOPT6: `Weekly Backup`,
    // priceYearlyInINR: 6699,
    priceTwoYearlyInINR: 46385,
    priceThreeYearlyInINR: 15795,
    priceTwoYearlyInUSD: 557,
    priceThreeYearlyInUSD: 190,
    priceTwoYearlyInEUR: 526,
    priceThreeYearlyInEUR: 179,
  },
  {
    id: 2,
    cardVpsTitle: "Premium",
    cardVpsSubTitle: "Ideal for personal websites",
    cardAnchorLink: `/virtual-server`,
    cardVpsImg: `https://madpopo.com/static/media/PopoPro.png`,
    cardVpsAltName: `Premium `,
    cardVpsOgPrice: `$24`,
    cardVpsWebSpace: "8",
    cardVpsCapacity: "E5 2670",
    cardVpsCapacity2: "32 GB",
    cardVpsCapacity3: "250 GB SSD",
    cardVpsSnap: "2 TB",
    cardVpsOPt1: "Free Domain 1st Year*",
    cardVpsOPT2: `5`,
    cardVpsOPT3: `20`,
    cardVpsOPT4: `50`,
    cardVpsOPT5: `10`,
    cardVpsOPT6: `Weekly Backup`,
    priceTwoYearlyInINR: 54485,
    priceThreeYearlyInINR: 18495,
    priceTwoYearlyInUSD: 654,
    priceThreeYearlyInUSD: 222,
    priceTwoYearlyInEUR: 617,
    priceThreeYearlyInEUR: 209,
  },
  {
    id: 3,
    cardVpsTitle: "Professional",
    cardVpsSubTitle: "Suitable for small business.",
    cardAnchorLink: `/virtual-server`,
    cardVpsImg: `https://madpopo.com/static/media/PopoGrow.png`,
    cardVpsAltName: `Professional`,
    cardVpsOgPrice: `$25`,
    cardVpsWebSpace: "10",
    cardVpsCapacity: "E5 2680 v2",
    cardVpsCapacity2: "64 GB",
    cardVpsCapacity3: "250 GB SSD",
    cardVpsSnap: "2 TB",
    cardVpsOPt1: "Free Domain 1st Year*",
    cardVpsOPT2: `10`,
    cardVpsOPT3: `30`,
    cardVpsOPT4: `100`,
    cardVpsOPT5: `20`,
    cardVpsOPT6: `Daily Backup`,
    priceTwoYearlyInINR: 61385,
    priceThreeYearlyInINR: 20795,
    priceTwoYearlyInUSD: 737,
    priceThreeYearlyInUSD: 250,
    priceTwoYearlyInEUR: 696,
    priceThreeYearlyInEUR: 235,
  },
  {
    id: 4,
    cardVpsTitle: "Enterprise",
    cardVpsSubTitle: "Suitable for small business.",
    cardAnchorLink: `/virtual-server`,
    cardVpsImg: `https://madpopo.com/static/media/PopoGrow.png`,
    cardVpsAltName: `Enterprise`,
    cardVpsOgPrice: `$25`,
    cardVpsWebSpace: "12",
    cardVpsCapacity: "E5 2678 v3",
    cardVpsCapacity2: "128 GB",
    cardVpsCapacity3: "250 GB SSD",
    cardVpsSnap: "2 TB",
    cardVpsOPt1: "Free Domain 1st Year*",
    cardVpsOPT2: `10`,
    cardVpsOPT3: `30`,
    cardVpsOPT4: `100`,
    cardVpsOPT5: `20`,
    cardVpsOPT6: `Daily Backup`,
    priceTwoYearlyInINR: 76985,
    priceThreeYearlyInINR: 25995,
    priceTwoYearlyInUSD: 924,
    priceThreeYearlyInUSD: 312,
    priceTwoYearlyInEUR: 873,
    priceThreeYearlyInEUR: 294,
  }, 

  // New Cards Add
  
  {
    id: 5,
    cardVpsTitle: "Level 1",
    cardVpsSubTitle: "Optimal solution for Beginners", 
    cardAnchorLink: `/virtual-server`,
    cardVpsImg: "https://madpopo.com/static/media/PopoStarter.png",
    cardVpsAltName: `Level 1`,
    cardVpsOgPrice: `$23`,
    cardVpsWebSpace: "12",
    cardVpsCapacity: "E5 2620 v3*2",
    cardVpsCapacity2: "32 GB",
    cardVpsCapacity3: "250 GB SSD",
    cardVpsSnap: "2 TB",
    cardVpsOPt1: "Free Domain 1st Year*",
    cardVpsOPT2: `1`,
    cardVpsOPT3: `10`,
    cardVpsOPT4: `20`,
    cardVpsOPT5: `2`,
    cardVpsOPT6: `Weekly Backup`,
    // priceYearlyInINR: 6699,
    priceTwoYearlyInINR: 66785,
    priceThreeYearlyInINR: 22595,
    priceTwoYearlyInUSD: 802,
    priceThreeYearlyInUSD: 271,
    priceTwoYearlyInEUR: 757,
    priceThreeYearlyInEUR: 256,
  },
  {
    id: 6,
    cardVpsTitle: "Level 2",
    cardVpsSubTitle: "Ideal for personal websites",
    cardAnchorLink: `/virtual-server`,
    cardVpsImg: `https://madpopo.com/static/media/PopoPro.png`,
    cardVpsAltName: `Level 2 `,
    cardVpsOgPrice: `$24`,
    cardVpsWebSpace: "16",
    cardVpsCapacity: "E5 2670*2",
    cardVpsCapacity2: "64 GB",
    cardVpsCapacity3: "250 GB SSD",
    cardVpsSnap: "2 TB",
    cardVpsOPt1: "Free Domain 1st Year*",
    cardVpsOPT2: `5`,
    cardVpsOPT3: `20`,
    cardVpsOPT4: `50`,
    cardVpsOPT5: `10`,
    cardVpsOPT6: `Weekly Backup`,
    priceTwoYearlyInINR: 76985,
    priceThreeYearlyInINR: 25995,
    priceTwoYearlyInUSD: 924,
    priceThreeYearlyInUSD: 312,
    priceTwoYearlyInEUR: 873,
    priceThreeYearlyInEUR: 294,
  },
  {
    id: 7,
    cardVpsTitle: "Level 3",
    cardVpsSubTitle: "Suitable for small business.",
    cardAnchorLink: `/virtual-server`,
    cardVpsImg: `https://madpopo.com/static/media/PopoGrow.png`,
    cardVpsAltName: `Level 3`,
    cardVpsOgPrice: `$25`,
    cardVpsWebSpace: "20",
    cardVpsCapacity: "E5 2680 v2*2",
    cardVpsCapacity2: "96 GB",
    cardVpsCapacity3: "250 GB SSD",
    cardVpsSnap: "2 TB",
    cardVpsOPt1: "Free Domain 1st Year*",
    cardVpsOPT2: `10`,
    cardVpsOPT3: `30`,
    cardVpsOPT4: `100`,
    cardVpsOPT5: `20`,
    cardVpsOPT6: `Daily Backup`,
    priceTwoYearlyInINR: 91985,
    priceThreeYearlyInINR: 30995,
    priceTwoYearlyInUSD: 1105,
    priceThreeYearlyInUSD: 372,
    priceTwoYearlyInEUR: 1043,
    priceThreeYearlyInEUR: 351,
  },
  {
    id: 8,
    cardVpsTitle: "Level 4",
    cardVpsSubTitle: "Suitable for small business.",
    cardAnchorLink: `/virtual-server`,
    cardVpsImg: `https://madpopo.com/static/media/PopoGrow.png`,
    cardVpsAltName: `Level 4`,
    cardVpsOgPrice: `$25`,
    cardVpsWebSpace: "24",
    cardVpsCapacity: "E5 2678 v3*2",
    cardVpsCapacity2: "128 GB",
    cardVpsCapacity3: "250 GB SSD",
    cardVpsSnap: "2 TB",
    cardVpsOPt1: "Free Domain 1st Year*",
    cardVpsOPT2: `10`,
    cardVpsOPT3: `30`,
    cardVpsOPT4: `100`,
    cardVpsOPT5: `20`,
    cardVpsOPT6: `Daily Backup`,
    priceTwoYearlyInINR: 93815,
    priceThreeYearlyInINR: 31605,
    priceTwoYearlyInUSD: 1127,
    priceThreeYearlyInUSD: 379,
    priceTwoYearlyInEUR: 1064,
    priceThreeYearlyInEUR: 358,
  },
  ];
  export default DDSData2;
  