const LinuxData = [
  {
    id: 1,
    cardlinuxTitle: "RockyBoost",
    Linkss: `/linux-web-hosting`,
    cardlinuxSubTitle: "Optimal solution for Beginners",
    cardlinuxOgPrice: `$32`,
    cardlinuxOffer: "offer - 30%",
    cardlinuxCapacity: "10GB",
    cardlinuxSSHAccess: "Unlimited",
    cardlinuxOPt1: "Free Domain 1st Year*",
    cardlinuxOPT2: `1`,
    cardlinuxOPT3: `10`,
    cardlinuxOPT4: `20`,
    cardlinuxOPT5: `2`,
    cardlinuxOPT6: `Weekly Backup`,
    priceYearlyInINR: 449,
    priceTwoYearlyInINR: 419,
    priceThreeYearlyInINR: 399,
    priceYearlyInUSD: 5.25,
    priceTwoYearlyInUSD: 4.92,
    priceThreeYearlyInUSD: 4.67,
    priceYearlyInEUR: 6,
    priceTwoYearlyInEUR: 5,
    priceThreeYearlyInEUR: 4,
  },
  {
    id: 2,
    cardlinuxTitle: "RockyPro",
    Linkss: `/linux-web-hosting`,
    cardlinuxSubTitle: "Ideal for personal websites",
    cardlinuxOgPrice: `$33`,
    cardlinuxOffer: "offer - 30%",
    cardlinuxCapacity: "20GB",
    cardlinuxSSHAccess: "Unlimited",
    cardlinuxOPt1: "Free Domain 1st Year*",
    cardlinuxOPT2: `5`,
    cardlinuxOPT3: `20`,
    cardlinuxOPT4: `50`,
    cardlinuxOPT5: `10`,
    cardlinuxOPT6: `Weekly Backup`,
    priceYearlyInINR: 549,
    priceTwoYearlyInINR: 519,
    priceThreeYearlyInINR: 499,
    priceYearlyInUSD: 6.42,
    priceTwoYearlyInUSD: 6.08,
    priceThreeYearlyInUSD: 5.86,
    priceYearlyInEUR: 7.2,
    priceTwoYearlyInEUR: 7,
    priceThreeYearlyInEUR: 6,
  },
  {
    id: 3,
    cardlinuxTitle: "RockyBusiness",
    Linkss: `/linux-web-hosting`,
    cardlinuxSubTitle: "Suitable for small business.",
    cardlinuxOgPrice: `$34`,
    cardlinuxOffer: "offer - 30%",
    cardlinuxCapacity: "30GB",
    cardlinuxSSHAccess: "Unlimited",
    cardlinuxOPt1: "Free Domain 1st Year*",
    cardlinuxOPT2: `10`,
    cardlinuxOPT3: `30`,
    cardlinuxOPT4: `100`,
    cardlinuxOPT5: `20`,
    cardlinuxOPT6: `Daily Backup`,
    priceYearlyInINR: 749,
    priceTwoYearlyInINR: 719,
    priceThreeYearlyInINR: 699,
    priceYearlyInUSD: 8.75,
    priceTwoYearlyInUSD: 8.46,
    priceThreeYearlyInUSD: 8.22,
    priceYearlyInEUR: 9.2,
    priceTwoYearlyInEUR: 9,
    priceThreeYearlyInEUR: 8,
  },
];
export default LinuxData;
