const ResellerHostingData = [
    {
      id: 1,
      resellerHostTitle: "Hosting 1", 
      resellerHostSubTitle: "Optimal solution for Beginners",
      resellerHostImg: "https://madpopo.com/static/media/PopoStarter.png",
      resellerHostAltName: `PopoStarter`,
      resellerHostOgPrice: `$23`,
      resellerHostWebSpace: "4",
      resellerHostCapacity: "8",
      resellerHostCapacity2: "50 GB",
      resellerHostCapacity3: "200 GB",
      resellerHostSnap: "1",
      resellerHostOPt1: "Free Domain 1st Year*",
      resellerHostOPT2: `1`,
      resellerHostOPT3: `10`,
      resellerHostOPT4: `20`,
      resellerHostOPT5: `2`,
      resellerHostOPT6: `Weekly Backup`,
      priceYearlyInINR: 699,
      priceTwoYearlyInINR: 599, 
      priceThreeYearlyInINR: 499,
      priceYearlyInUSD: 8.5,
      priceTwoYearlyInUSD: 7.5,
      priceThreeYearlyInUSD: 6.5,
      priceYearlyInEUR: 8,
      priceTwoYearlyInEUR: 7,
      priceThreeYearlyInEUR: 6,
    },
    {
      id: 2,
      resellerHostTitle: "Hosting 2 ",
      resellerHostSubTitle: "Ideal for personal websites",
      resellerHostImg: `https://madpopo.com/static/media/PopoPro.png`,
      resellerHostAltName: `PopoPro `,
      resellerHostOgPrice: `$24`,
      resellerHostWebSpace: "6",
      resellerHostCapacity: "16",
      resellerHostCapacity2: "100 GB",
      resellerHostCapacity3: "400 GB",
      resellerHostSnap: "2",
      resellerHostOPt1: "Free Domain 1st Year*",
      resellerHostOPT2: `5`,
      resellerHostOPT3: `20`,
      resellerHostOPT4: `50`,
      resellerHostOPT5: `10`,
      resellerHostOPT6: `Weekly Backup`,
      priceYearlyInINR: 899,
      priceTwoYearlyInINR: 799,
      priceThreeYearlyInINR: 699,
      priceYearlyInUSD: 12.5,
      priceTwoYearlyInUSD: 9.5,
      priceThreeYearlyInUSD: 8.5,
      priceYearlyInEUR: 12,
      priceTwoYearlyInEUR: 9,
      priceThreeYearlyInEUR: 8,
    },
    {
      id: 3,
      resellerHostTitle: "Hosting 3",
      resellerHostSubTitle: "Suitable for small business.",
      resellerHostImg: `https://madpopo.com/static/media/PopoGrow.png`,
      resellerHostAltName: `PopoGrow`,
      resellerHostOgPrice: `$25`,
      resellerHostWebSpace: "10",
      resellerHostCapacity: "60",
      resellerHostCapacity2: "400 GB",
      resellerHostCapacity3: "1.6 TB",
      resellerHostSnap: "4",
      resellerHostOPt1: "Free Domain 1st Year*",
      resellerHostOPT2: `10`,
      resellerHostOPT3: `30`,
      resellerHostOPT4: `100`,
      resellerHostOPT5: `20`,
      resellerHostOPT6: `Daily Backup`,
      priceYearlyInINR: 1199,
      priceTwoYearlyInINR: 1099,
      priceThreeYearlyInINR: 999,
      priceYearlyInUSD: 14.5,
      priceTwoYearlyInUSD: 13.5,
      priceThreeYearlyInUSD: 12.5,
      priceYearlyInEUR: 14,
      priceTwoYearlyInEUR: 13,
      priceThreeYearlyInEUR: 12,
    },
  ];
  export default ResellerHostingData;
  