const VpsData = [
  {
    id: 1,
    cardVpsTitle: "Starter",
    cardVpsSubTitle: "Optimal solution for Beginners", 
    cardAnchorLink: `/virtual-server`,
    cardVpsImg: "https://madpopo.com/static/media/PopoStarter.png",
    cardVpsAltName: `Starter`,
    cardVpsOgPrice: `$23`,
    cardVpsWebSpace: "3",
    cardVpsCapacity: "24",
    cardVpsCapacity2: "180 GB NVMe",
    cardVpsCapacity3: "200 GB",
    cardVpsSnap: "1",
    cardVpsOPt1: "Free Domain 1st Year*",
    cardVpsOPT2: `1`,
    cardVpsOPT3: `10`,
    cardVpsOPT4: `20`,
    cardVpsOPT5: `2`,
    cardVpsOPT6: `Weekly Backup`,
    priceYearlyInINR: 6699,
    priceTwoYearlyInINR: 6399,
    priceThreeYearlyInINR: 5999,
    priceYearlyInUSD: 78.75,
    priceTwoYearlyInUSD: 75.25,
    priceThreeYearlyInUSD: 70.56,
    priceYearlyInEUR: 76,
    priceTwoYearlyInEUR: 73,
    priceThreeYearlyInEUR: 68,
    title: "Virtual Dedicated Server - Starter Plan",
  },
  {
    id: 2,
    cardVpsTitle: "Pro ",
    cardVpsSubTitle: "Ideal for personal websites",
    cardAnchorLink: `/virtual-server`,
    cardVpsImg: `https://madpopo.com/static/media/PopoPro.png`,
    cardVpsAltName: `Pro `,
    cardVpsOgPrice: `$24`,
    cardVpsWebSpace: "6",
    cardVpsCapacity: "48",
    cardVpsCapacity2: "360 GB NVMe",
    cardVpsCapacity3: "400 GB",
    cardVpsSnap: "2",
    cardVpsOPt1: "Free Domain 1st Year*",
    cardVpsOPT2: `5`,
    cardVpsOPT3: `20`,
    cardVpsOPT4: `50`,
    cardVpsOPT5: `10`,
    cardVpsOPT6: `Weekly Backup`,
    priceYearlyInINR: 11699,
    priceTwoYearlyInINR: 11399,
    priceThreeYearlyInINR: 9999,
    priceYearlyInUSD: 137.58,
    priceTwoYearlyInUSD: 134.08,
    priceThreeYearlyInUSD: 117.61,
    priceYearlyInEUR: 133,
    priceTwoYearlyInEUR: 130,
    priceThreeYearlyInEUR: 114,
    title: "Virtual Dedicated Server - Pro Plan",
  },
  {
    id: 3,
    cardVpsTitle: "Grow",
    cardVpsSubTitle: "Suitable for small business.",
    cardAnchorLink: `/virtual-server`,
    cardVpsImg: `https://madpopo.com/static/media/PopoGrow.png`,
    cardVpsAltName: `Grow`,
    cardVpsOgPrice: `$25`,
    cardVpsWebSpace: "12",
    cardVpsCapacity: "96",
    cardVpsCapacity2: "720 GB NVMe",
    cardVpsCapacity3: "1.6 TB",
    cardVpsSnap: "4",
    cardVpsOPt1: "Free Domain 1st Year*",
    cardVpsOPT2: `10`,
    cardVpsOPT3: `30`,
    cardVpsOPT4: `100`,
    cardVpsOPT5: `20`,
    cardVpsOPT6: `Daily Backup`,
    priceYearlyInINR: 18699,
    priceTwoYearlyInINR: 18399,
    priceThreeYearlyInINR: 17999,
    priceYearlyInUSD: 219.92,
    priceTwoYearlyInUSD: 216.46,
    priceThreeYearlyInUSD: 211.75,
    priceYearlyInEUR: 213,
    priceTwoYearlyInEUR: 209,
    priceThreeYearlyInEUR: 205,
    title: "Virtual Dedicated Server - Grow Plan",
  },
];
export default VpsData;
