const VssData = [
  {
    id: 1,
    cardVpsTitle: "Starter",
    cardVpsSubTitle: "Optimal solution for Beginners",
    cardAnchorLink: `/virtual-server`,
    cardVpsImg: "https://madpopo.com/image/PopoStarter.png",
    cardVpsAltName: `Starter`,
    cardVpsOgPrice: `$23`,
    cardVpsWebSpace: "2",
    cardVpsCapacity: "4",
    cardVpsCapacity2: "400 GB SSD",
    cardVpsCapacity3: "200 GB",
    cardVpsSnap: "1",
    cardVpsOPt1: "Free Domain 1st Year*",
    cardVpsOPT2: `1`,
    cardVpsOPT3: `10`,
    cardVpsOPT4: `20`,
    cardVpsOPT5: `2`,
    cardVpsOPT6: `Weekly Backup`,
    priceYearlyInINR: 1699,
    priceTwoYearlyInINR: 1399,
    priceThreeYearlyInINR: 999,
    priceYearlyInUSD: 19.92,
    priceTwoYearlyInUSD: 16.46,
    priceThreeYearlyInUSD: 11.75,
    priceYearlyInEUR: 21,
    priceTwoYearlyInEUR: 19,
    priceThreeYearlyInEUR: 18,
    width: 131,
    height: 165,
  },
  {
    id: 2,
    cardVpsTitle: "Pro",
    cardVpsSubTitle: "Ideal for personal websites",
    cardAnchorLink: `/virtual-server`,
    cardVpsImg: `https://madpopo.com/image/PopoPro.png`,
    cardVpsAltName: `Pro `,
    cardVpsOgPrice: `$24`,
    cardVpsWebSpace: "4",
    cardVpsCapacity: "8",
    cardVpsCapacity2: "800 GB SSD",
    cardVpsCapacity3: "400 GB",
    cardVpsSnap: "2",
    cardVpsOPt1: "Free Domain 1st Year*",
    cardVpsOPT2: `5`,
    cardVpsOPT3: `20`,
    cardVpsOPT4: `50`,
    cardVpsOPT5: `10`,
    cardVpsOPT6: `Weekly Backup`,
    priceYearlyInINR: 2699,
    priceTwoYearlyInINR: 2399,
    priceThreeYearlyInINR: 1999,
    priceYearlyInUSD: 31.75,
    priceTwoYearlyInUSD: 28.21,
    priceThreeYearlyInUSD: 23.5,
    priceYearlyInEUR: 26,
    priceTwoYearlyInEUR: 25,
    priceThreeYearlyInEUR: 24,
    width: 131,
    height: 165,
  },
  {
    id: 3,
    cardVpsTitle: "Grow",
    cardVpsSubTitle: "Suitable for small business.",
    cardAnchorLink: `/virtual-server`,
    cardVpsImg: `https://madpopo.com/image/PopoGrow.png`,
    cardVpsAltName: `Grow`,
    cardVpsOgPrice: `$25`,
    cardVpsWebSpace: "8",
    cardVpsCapacity: "32",
    cardVpsCapacity2: "3.2 TB SSD",
    cardVpsCapacity3: "1.6 TB",
    cardVpsSnap: "4",
    cardVpsOPt1: "Free Domain 1st Year*",
    cardVpsOPT2: `10`,
    cardVpsOPT3: `30`,
    cardVpsOPT4: `100`,
    cardVpsOPT5: `20`,
    cardVpsOPT6: `Daily Backup`,
    priceYearlyInINR: 5699,
    priceTwoYearlyInINR: 5399,
    priceThreeYearlyInINR: 4999,
    priceYearlyInUSD: 67,
    priceTwoYearlyInUSD: 63.5,
    priceThreeYearlyInUSD: 58.81,
    priceYearlyInEUR: 52,
    priceTwoYearlyInEUR: 51,
    priceThreeYearlyInEUR: 49,
    width: 131,
    height: 165,
  },
];
export default VssData;
