const WindowsHostingDatas = [
  {
    id: 1,
    winHostTitle: "WinStarter",
    winHostSubTitle: "Optimal solution for Beginners",
    winHostAnchor: "/windows-hosting",
    winHostOgPrice: `$32.99`,
    winHostDiscPrice: `$30.99`,
    winHostOffer: "offer - 30%",
    winHostCapacity: "5GB",
    winHostSSHAccess: "Unlimited", 
    winHostDDOS: "1", 
    winHOPt1: "10",
    winHOPt2: `20`,
    winHOPt3: `2`,
    winHOPt4: `20`,
    winHOPt5: `2`,
    winHOPt6: `Weekly Backup`,
    priceYearlyInINR: 449,
    priceTwoYearlyInINR: 419,
    priceThreeYearlyInINR: 399,
    priceYearlyInUSD: 5.25,
    priceTwoYearlyInUSD: 4.92,
    priceThreeYearlyInUSD: 4.67,
    priceYearlyInEUR: 6,
    priceTwoYearlyInEUR: 5,
    priceThreeYearlyInEUR: 4,
  },
  {
    id: 2,
    winHostTitle: "WinPro",
    winHostSubTitle: "Ideal for personal websites",
    winHostAnchor: "/windows-hosting",
    winHostOgPrice: `$33.99`,
    winHostDiscPrice: `$31.99`,
    winHostOffer: "offer - 40%",
    winHostCapacity: "10GB",
    winHostSSHAccess: "Unlimited",
    winHostDDOS: "5",
    winHOPt1: "20",
    winHOPt2: `50`,
    winHOPt3: `10`,
    winHOPt4: `20`,
    winHOPt5: `2`,
    winHOPt6: `Weekly Backup`,
    priceYearlyInINR: 549,
    priceTwoYearlyInINR: 519,
    priceThreeYearlyInINR: 499,
    priceYearlyInUSD: 6.42,
    priceTwoYearlyInUSD: 6.08,
    priceThreeYearlyInUSD: 5.86,
    priceYearlyInEUR: 7.2,
    priceTwoYearlyInEUR: 7,
    priceThreeYearlyInEUR: 6,
  },
  {
    id: 3,
    winHostTitle: "WinGrow",
    winHostSubTitle: "Suitable for small business",
    winHostAnchor: "/windows-hosting",
    winHostOgPrice: `$34.99`,
    winHostDiscPrice: `$32.99`,
    winHostOffer: "offer - 30%",
    winHostCapacity: "20GB",
    winHostSSHAccess: "Unlimited",
    winHNode: `10`,
    winHostDDOS: "10",
    winHOPt1: "30",
    winHOPt2: `100`,
    winHOPt3: `20`,
    winHOPt4: `20`,
    winHOPt5: `2`,
    winHOPt6: `Daily Backup`,
    priceYearlyInINR: 749,
    priceTwoYearlyInINR: 719,
    priceThreeYearlyInINR: 699,
    priceYearlyInUSD: 8.75,
    priceTwoYearlyInUSD: 8.46,
    priceThreeYearlyInUSD: 8.22,
    priceYearlyInEUR: 9.2,
    priceTwoYearlyInEUR: 9,
    priceThreeYearlyInEUR: 8,
  },
];
export default WindowsHostingDatas;
