const domainListData = [
    {
        id:1,
        domainName: `.ACADEMY`,
        domainRgister: `29.10`, 
        domainRenew: `29.10`,
        domainTransfer: `29.10`,
    },
    {
        id:2,
        domainName: `.ACCOUNTANT (On Promo)`,
        domainRgister: `34.99`,
        domainRenew: `5.89`,
        domainTransfer: `5.89`,
    },
    {
        id:3,
        domainName: `.ACCOUNTANTS`,
        domainRgister: `115.29`,
        domainRenew: `115.29`,
        domainTransfer: `115.29`,
    },
    {
        id:4,
        domainName: `.ACTOR`,
        domainRgister: `43.79`,
        domainRenew: `43.79`,
        domainTransfer: `43.79`,
    },
    {
        id:5,
        domainName: `.ADULT`,
        domainRgister: `109.49`,
        domainRenew: `109.49`,
        domainTransfer: `109.49`,
    },
    {
        id:6,
        domainName: `.AIRFORCE`,
        domainRgister: `29.99`,
        domainRenew: `29.99`,
        domainTransfer: `29.99`,
    },
    {
        id:7,
        domainName: `.AMSTERDAM`,
        domainRgister: `43.19`,
        domainRenew: `43.19`,
        domainTransfer: `43.19`,
    },
    {
        id:8,
        domainName: `.ARCHI (On Promo)`,
        domainRgister: `73.19`,
        domainRenew: `73.19`,
        domainTransfer: `73.19`,
    },
    {
        id:9,
        domainName: `.ARMY`,
        domainRgister: `34.99`,
        domainRenew: `34.99`,
        domainTransfer: `34.99`,
    },
    {
        id:10,
        domainName: `.ART Pre-GA`,
        domainRgister: `13.22`,
        domainRenew: `13.22`,
        domainTransfer: `13.22`,
    },
    {
        id:11,
        domainName: `.ASIA (On Promo)`,
        domainRgister: `24.00`,
        domainRenew: `24.00`,
        domainTransfer: `24.00`,
    },
    {
        id:12,
        domainName: `.ASSOCIATES`,
        domainRgister: `34.99`,
        domainRenew: `34.99`,
        domainTransfer: `34.99`,
    },
    {
        id:13,
        domainName: `.ATTORNEY (On Promo)`,
        domainRgister: `43.79`,
        domainRenew: `43.79`,
        domainTransfer: `43.79`,
    },
    {
        id:14,
        domainName: `.AU 3rd Level`,
        domainRgister: `18.00`,
        domainRenew: `18.00`,
        domainTransfer: `18.00`,
    },
    {
        id:15,
        domainName: `.AUCTION`,
        domainRgister: `34.99`,
        domainRenew: `34.99`,
        domainTransfer: `34.99`,
    },
    {
        id:16,
        domainName: `.AUDIO`,
        domainRgister: `16.29`,
        domainRenew: `16.29`,
        domainTransfer: `16.29`,
    },
    {
        id:17,
        domainName: `.AUTO`,
        domainRgister: `2881.19`,
        domainRenew: `2881.19`,
        domainTransfer: `2881.19`,
    },
    {
        id:18,
        domainName: `.BAND`,
        domainRgister: `26.29`,
        domainRenew: `26.29`,
        domainTransfer: `26.29`,
    },
    {
        id:19,
        domainName: `.BAR`,
        domainRgister: `87.59`,
        domainRenew: `87.59`,
        domainTransfer: `87.59`,
    },
    {
        id:20,
        domainName: `.BARGAINS`,
        domainRgister: `34.99`,
        domainRenew: `34.99`,
        domainTransfer: `34.99`,
    },
    
]

export default domainListData;