const woocomPriceData = {
    mainDataPricing: [
      {
        id: 1,
        cardTitle: "Popo Store Easy",
        cardSubTitle: "Optimal solution for Beginners",
        cardOgPrice: `$32`,
        cardOffer: "offer - 30%",
        cardCapacity: "10GB",
        cardSSHAccess: "Unlimited", 
        cardDDOS: "Save $399",
        wpNode:`1`,
        wpWeeklyBckp:`Weekly Backup`,
        wordpressHostingTitle: "POPO - L",
      },
      {
        id: 2,
        cardTitle: "Popo Store Pro",
        cardSubTitle: "Ideal for personal websites",
        cardOgPrice: `$33`,
        cardOffer: "offer - 40%",
        cardCapacity: "20GB",
        cardSSHAccess: "Unlimited",
        cardDDOS: "Save $399",
        wpNode:`5`,
        wpWeeklyBckp:`Weekly Backup`,
        wordpressHostingTitle: "POPO - XL",
      },
      {
        id: 3,
        cardTitle: "Popo Store Master",
        cardSubTitle: "Suitable for small business",
        cardOgPrice: `$34`,
        cardOffer: "offer - 30%",
        cardCapacity: "30GB",
        cardSSHAccess: "Unlimited",
        wpNode:`10`,
        cardDDOS: "Save $399",
        wpWeeklyBckp:`Daily Backup`,
        wordpressHostingTitle: "POPO - XXL",
      },
    ],
    pricingValues: {
      1: [
        {
          id: 1,
          label: "1 Year",
          cardPrice1: "$19.99",
          cardPrice2: "$15.99",
          cardPrice3: "$11.99",
        },
        //   {
        //     id: 12,
        //     cardPrice: "$269.99",
        //     cardPrice2: "$270.99",
        //     cardPrice3: "$271.99",
        //   },
        //   {
        //     id: 13,
        //     cardPrice: "$289.99",
        //     cardPrice2: "$290.99",
        //     cardPrice3: "$291.99",
        //   },
      ],
      2: [
        {
          id: 2,
          label: "2 Years",
          cardPrice1: "$20",
          cardPrice2: "$21",
          cardPrice3: "$22",
        },
        //   {
        //     id: 22,
        //     cardPrice: "$269.99",
        //     cardPrice2: "$270.99",
        //     cardPrice3: "$271.99",
        //   },
        //   {
        //     id: 23,
        //     cardPrice: "$289.99",
        //     cardPrice2: "$290.99",
        //     cardPrice3: "$291.99",
        //   },
      ],
      3: [
        {
          id: 3,
          label: "3 Years",
          cardPrice1: "$30",
          cardPrice2: "$31",
          cardPrice3: "$32",
        },
        //   {
        //     id: 32,
        //     cardPrice: "$269.99",
        //     cardPrice2: "$270.99",
        //     cardPrice3: "$271.99",
        //   },
        //   {
        //     id: 34,
        //     cardPrice: "$289.99",
        //     cardPrice2: "$290.99",
        //     cardPrice3: "$291.99",
        //   },
      ],
    },
  };
  export default woocomPriceData;
  