const RightData = [
  {
    id: 0,
    planTitle: "WooCommerce Hosting",
    planPiceF: "449",
    planPiceF2: "5.48",
    planPiceF3: "4.97",
    planPiceFUSD: "12",
    planPiceFEUR: "8.8",
    planPicePaisa: "/ month",
    // planCurrency : '₹',
    planOffer: "Save 40%",
    planIcon: <i className="feather icon-check"></i>,
    planList1: "WordPress Hosting        ",
    planList2: "20 GB Web Space        ",
    planList3: "Unmetered Traffic        ",
    planList4: "Free SSL & Enhanced Security",
    planList5: "Managed WordPress        ",
    bgColor:
      "linear-gradient(162deg, rgba(9,187,254,1) 13%, rgba(86,72,237,1) 66%)",
    smallTitleColor: "#fff",
    planbadgeBgColor: "#ecebfd",
    planbadgeTextColor: "#000",
    billedCat: "Triannually",
    link:'/woocommerce-hosting'
  },
  {
    id: 1,
    planTitle: " Professional Business Email",
    planPiceF: "125",
    planPiceF2: "1.53",
    planPiceF3: "1.38",
    planPicePaisa: "/ month",
    // planCurrency : '₹',
    planOffer: "Save 40%",
    planIcon: <i className="feather icon-check"></i>,
    planList1: "Commercial License",
    planList2: "30GB Storage        ",
    planList3: "Never miss a meeting        ",
    planList4: "Communicate on the go        ",
    planList5: "Intelligent Collaboration        ",
    bgColor:
      "linear-gradient(150deg, rgba(9,187,254,1) 36%, rgba(74,201,237,1) 70%)",
    billedCat: "Triannually",
    link:'/business-email-hosting'
  },
  {
    id: 2,
    planTitle: "Premium SSL Certificate",
    planPiceF: "02.5",
    planPiceF2: "0.031",
    planPiceF3: "0.028",
    planPicePaisa: "/ month",
    //  planCurrency : '₹',
    planOffer: "Save 40%",
    planIcon: <i className="feather icon-check"></i>,
    planList1: "Commercial License",
    planList2: "Domain Validation         ",
    planList3: "Solid Security",
    planList4: "Increase SEO Ranking",
    planList5: "$10,000 warranty level         ",
    bgColor:
      "linear-gradient(150deg, rgba(9,187,254,1) 36%, rgba(74,237,180,1) 70%)",
    billedCat: "Triannually",
    link:'/ssl-certificate'
  },
  {
    id: 3,
    planTitle: "250GB/ Object Storage         ",
    planPiceF: "325",
    planPiceF2: "3.97",
    planPiceF3: "3.60",
    planPicePaisa: "/ month",
    //  planCurrency : '₹',
    planOffer: "Save 40%",
    planIcon: <i className="feather icon-check"></i>,
    planList1: "Commercial License",
    planList2: "S3-Compatible API         ",
    planList3: "Always-On DDos Protection         ",
    planList4: "Guaranteed Redundancy         ",
    planList5: "Works Well with Any Serve",
    bgColor:
      "linear-gradient(150deg, rgba(9,187,254,1) 36%, rgba(237,213,74,1) 70%)",
    billedCat: "Monthly",
    // link: '/object-storage'
    link: ''
  },
];

export default RightData;
